"""IPAD — Inverse Prompt for AI Detection.

Reference:
    Chen et al., "IPAD: Inverse Prompt for AI Detection", NeurIPS 2025.

IPAD is a three-module framework built on LoRA-fine-tuned
``microsoft/Phi-3-medium-128k-instruct`` models hosted at
``bellafc/IPAD/`` on HuggingFace:

1. **Prompt Inverter** (``bellafc/IPAD/Prompt_Inverter``): predicts the
   most likely prompt that produced the input text.
2. **PTCV** (Prompt-Text Consistency Verifier,
   ``bellafc/IPAD/Distinguisher_PTCV``): scores whether the text could
   plausibly have been generated from the inverted prompt.
3. **RC** (Regeneration Comparator,
   ``bellafc/IPAD/Distinguisher_RC``): regenerates text from the inverted
   prompt and compares with the original.

The final score fuses PTCV and RC probabilities:
    p̂ = w * p_PTCV + (1 − w) * p_RC

When PEFT adapters are unavailable (``use_peft=False``), falls back
to a simplified zero-shot proxy using a causal LM.
"""

from __future__ import annotations

from typing import Any

import torch
import torch.nn.functional as F

from detectzoo.core.base import DetectionResult
from detectzoo.core.registry import register_detector
from detectzoo.detectors.text.base import BaseTextDetector
from detectzoo.utils.logger import get_logger

logger = get_logger(__name__)

_BASE_MODEL = "microsoft/Phi-3-medium-128k-instruct"
_INVERTER_ADAPTER = "bellafc/IPAD/Prompt_Inverter"
_PTCV_ADAPTER = "bellafc/IPAD/Distinguisher_PTCV"
_RC_ADAPTER = "bellafc/IPAD/Distinguisher_RC"

_INVERTER_TEMPLATE = (
    "Given the following text, predict the most likely prompt that "
    "could have generated it:\n\n{text}\n\nPredicted prompt:"
)
_PTCV_TEMPLATE = (
    "Text 1 is generated by LLM, determine whether text 2 is also "
    "generated by LLM with a similar prompt.\n"
    "Prompt: {prompt}\nText: {text}\nAnswer:"
)
_RC_TEMPLATE = "Can LLM generate the input text {text} through the prompt {prompt}?"


@register_detector("ipad")
class IPADDetector(BaseTextDetector):
    """IPAD detector — inverse-prompt consistency scoring.

    When ``use_peft=True`` (default), loads the three official LoRA
    adapters on top of Phi-3-medium-128k-instruct.

    When ``use_peft=False``, uses a lightweight causal LM proxy that
    measures conditional vs unconditional log-probability.

    Parameters:
        model_name: Base model for the LoRA adapters (default
            ``"microsoft/Phi-3-medium-128k-instruct"``).
        use_peft: Load official LoRA adapters (default ``True``).
        fusion_weight: Weight *w* for fusing PTCV and RC scores
            (default ``0.5``).
        max_new_tokens: Tokens generated for prompt inversion.
        threshold: Decision boundary.
        device: ``"cpu"`` or ``"cuda"``.
    """

    def __init__(
        self,
        model_name: str = _BASE_MODEL,
        use_peft: bool = True,
        fusion_weight: float = 0.5,
        max_new_tokens: int = 128,
        threshold: float = 0.5,
        device: str = "cpu",
        max_length: int = 512,
        **kwargs: Any,
    ) -> None:
        super().__init__(
            model_name=model_name,
            threshold=threshold,
            device=device,
            max_length=max_length,
            **kwargs,
        )
        self.use_peft = use_peft
        self.fusion_weight = fusion_weight
        self.max_new_tokens = max_new_tokens

        self._inverter_model: torch.nn.Module | None = None
        self._ptcv_model: torch.nn.Module | None = None
        self._rc_model: torch.nn.Module | None = None
        self._ipad_tokenizer: Any = None

    # ------------------------------------------------------------------
    # Model loading
    # ------------------------------------------------------------------

    def _load_model(self) -> None:
        if self.use_peft:
            self._load_peft_models()
        else:
            self._load_fallback_model()

    def _load_peft_models(self) -> None:
        from transformers import AutoModelForCausalLM, AutoTokenizer

        logger.info("Loading IPAD base model '%s' …", self.model_name)
        self._ipad_tokenizer = AutoTokenizer.from_pretrained(self.model_name)
        if self._ipad_tokenizer.pad_token is None:
            self._ipad_tokenizer.pad_token = self._ipad_tokenizer.eos_token

        try:
            from peft import PeftModel

            base = AutoModelForCausalLM.from_pretrained(
                self.model_name,
                torch_dtype=torch.float16,
                device_map=self._device,
            )
            base.eval()

            logger.info("Loading IPAD Prompt Inverter adapter …")
            self._inverter_model = PeftModel.from_pretrained(
                base,
                _INVERTER_ADAPTER,
            )
            self._inverter_model.eval()

            logger.info("Loading IPAD PTCV adapter …")
            base_ptcv = AutoModelForCausalLM.from_pretrained(
                self.model_name,
                torch_dtype=torch.float16,
                device_map=self._device,
            )
            self._ptcv_model = PeftModel.from_pretrained(
                base_ptcv,
                _PTCV_ADAPTER,
            )
            self._ptcv_model.eval()

            logger.info("Loading IPAD RC adapter …")
            base_rc = AutoModelForCausalLM.from_pretrained(
                self.model_name,
                torch_dtype=torch.float16,
                device_map=self._device,
            )
            self._rc_model = PeftModel.from_pretrained(
                base_rc,
                _RC_ADAPTER,
            )
            self._rc_model.eval()

        except Exception as exc:
            logger.warning(
                "Failed to load PEFT adapters (%s); falling back to zero-shot proxy.",
                exc,
            )
            self.use_peft = False
            self._load_fallback_model()

    def _load_fallback_model(self) -> None:
        from transformers import AutoModelForCausalLM, AutoTokenizer

        fallback = "gpt2" if self.model_name == _BASE_MODEL else self.model_name
        logger.info("Loading IPAD fallback model '%s' …", fallback)
        self._ipad_tokenizer = AutoTokenizer.from_pretrained(fallback)
        if self._ipad_tokenizer.pad_token is None:
            self._ipad_tokenizer.pad_token = self._ipad_tokenizer.eos_token
        self._model = AutoModelForCausalLM.from_pretrained(fallback).to(self._device)
        self._model.eval()

    @property
    def ipad_tokenizer(self):
        if self._ipad_tokenizer is None:
            self._load_model()
        return self._ipad_tokenizer

    # ------------------------------------------------------------------
    # PEFT-based prediction (full pipeline)
    # ------------------------------------------------------------------

    def _softmax_prob(self, model: torch.nn.Module, prompt: str) -> float:
        """Extract binary 'Yes'/'No' probability from a distinguisher."""
        enc = self.ipad_tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=self.max_length,
        ).to(self._device)

        with torch.no_grad():
            logits = model(**enc).logits[:, -1, :]

        yes_id = self.ipad_tokenizer.encode("Yes", add_special_tokens=False)
        no_id = self.ipad_tokenizer.encode("No", add_special_tokens=False)

        if yes_id and no_id:
            pair_logits = torch.tensor([logits[0, no_id[0]].item(), logits[0, yes_id[0]].item()])
            probs = torch.softmax(pair_logits, dim=0)
            return float(probs[1])

        return float(torch.softmax(logits, dim=-1).max())

    @torch.no_grad()
    def _invert_prompt_peft(self, text: str) -> str:
        prompt = _INVERTER_TEMPLATE.format(text=text[:1024])
        enc = self.ipad_tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=self.max_length,
        ).to(self._device)

        out = self._inverter_model.generate(  # type: ignore[union-attr]
            **enc,
            max_new_tokens=self.max_new_tokens,
            do_sample=False,
        )
        generated = out[0][enc["input_ids"].shape[1] :]
        return self.ipad_tokenizer.decode(generated, skip_special_tokens=True).strip()

    def _predict_peft(self, text: str) -> DetectionResult:
        predicted_prompt = self._invert_prompt_peft(text)

        ptcv_input = _PTCV_TEMPLATE.format(prompt=predicted_prompt, text=text[:512])
        p_ptcv = self._softmax_prob(self._ptcv_model, ptcv_input)  # type: ignore[arg-type]

        rc_input = _RC_TEMPLATE.format(prompt=predicted_prompt, text=text[:512])
        p_rc = self._softmax_prob(self._rc_model, rc_input)  # type: ignore[arg-type]

        score = self.fusion_weight * p_ptcv + (1 - self.fusion_weight) * p_rc

        return self._make_result(
            score,
            p_ptcv=p_ptcv,
            p_rc=p_rc,
            inverted_prompt=predicted_prompt[:200],
        )

    # ------------------------------------------------------------------
    # Fallback zero-shot prediction
    # ------------------------------------------------------------------

    @torch.no_grad()
    def _invert_prompt_simple(self, text: str) -> str:
        words = text.split()
        return " ".join(words[: min(30, len(words))])

    @torch.no_grad()
    def _conditional_logprob(self, prompt: str, text: str) -> float:
        combined = prompt + " " + text
        enc = self.ipad_tokenizer(
            combined,
            return_tensors="pt",
            truncation=True,
            max_length=self.max_length,
        ).to(self._device)

        prompt_enc = self.ipad_tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=self.max_length,
        )
        prompt_len = prompt_enc["input_ids"].shape[1]

        logits = self.model(**enc).logits
        log_probs = F.log_softmax(logits[:, :-1, :], dim=-1)
        ids = enc["input_ids"][:, 1:]
        token_lp = log_probs.gather(2, ids.unsqueeze(-1)).squeeze(-1).squeeze(0)

        if prompt_len < len(token_lp):
            text_lp = token_lp[prompt_len - 1 :]
            return float(text_lp.mean())
        return float(token_lp.mean())

    def _predict_fallback(self, text: str) -> DetectionResult:
        prompt = self._invert_prompt_simple(text)
        cond_lp = self._conditional_logprob(prompt, text)
        uncond_lp = self._mean_log_prob(text)

        score = cond_lp - uncond_lp

        return self._make_result(
            score,
            conditional_logprob=cond_lp,
            unconditional_logprob=uncond_lp,
            inverted_prompt=prompt[:100],
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def predict(self, input_data: Any) -> DetectionResult:
        text = self._normalise_input(input_data)

        if self._inverter_model is None and self.use_peft:
            self._load_model()

        if self.use_peft and self._inverter_model is not None:
            return self._predict_peft(text)

        if self._model is None:
            self._load_model()
        return self._predict_fallback(text)
